from time import sleep
import os

def real_val(s):
    return int(s.split('-')[1])

while True:
    files = os.listdir()
    print('Cleaning')

    deleteable = []

    for file in files:
        if ".hlt" in file:
            os.remove(file)
        if "AutoGenerated" in file:
            deleteable.append(file)

    deleteable.sort(key=real_val)
    if len(deleteable) > 3:
        for file in deleteable[:-3]:
            os.remove(file)
    sleep(10)